# Periodically regenerates the CDI-SDN-Py library from the current OpenAPI.json file 
# # from the website. 
# name: Generate Python Client
# on:
#   schedule:
#     # Cron trigger for once a week, on a Sunday, at midnight
#     - cron:  '0 0 * * 0'

jobs:
  generate-python-client:
    runs-on: ubuntu-latest
    name: Client Gen
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Python Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          config-file: python-generator-config.yml

      # Do something with the generated client (likely publishing it somewhere)
      - name: Do something with the client
        run: |
          cd typescript-angular-client
